# Topic modeling configuration for insurance complaints dataset

preprocessing:
  normalization:
    lowercase: true
    remove_punctuation: true
    remove_numbers: false
    lemmatize: true
    language: "en"
  stopwords:
    use_default: true
    additional:
      - "dear"
      - "insurance"
      - "company"
      - "sincerely"
      - "writing"
      - "regards"
      - "customer"
      - "policy"
      - "claim"
      - "letter"
      - "email"
      - "complaint"
      - "frustration"

modeling:
  embeddings:
    model_name: "all-MiniLM-L6-v2"  # Small, fast model for demonstration
    batch_size: 32
  lda:
    num_topics: 10
    passes: 5
    iterations: 50
    alpha: "auto"
    eta: "auto"
  clustering:
    algorithm: "kmeans"
    n_clusters: 9
    min_cluster_size: 15
    min_samples: 5
    cluster_selection_method: "eom"
  topic_matching:
    threshold: 0.15  # Lower threshold to assign more topics
    assign_multiple: true
    max_topics_per_doc: 3

visualization:
  umap:
    n_neighbors: 15
    min_dist: 0.1
    n_components: 2
    metric: "cosine"
  plots:
    width: 900
    height: 700
    marker_size: 6
    opacity: 0.8
    colorscale: "Viridis"

reporting:
  html:
    title: "Insurance Complaints Topic Analysis"
    subtitle: "Analysis of Australian Insurance PII Dataset"
    include_interactive: true
    max_docs_per_topic: 10
    template_path: null  # Use default template
  export:
    formats:
      - "csv"
      - "json"
    include_embeddings: false